### ISSUE TITLE
cannot build extension

### ISSUE THREAD

**Issue by joshoohaah** [microsoft/AzureDevOps-WSJF-Extension#16]
When i try to build this i get the error below when i run `npm run build`

```
node_modules/typescript/lib/lib.dom.d.ts:12377:11 - error TS2320: Interface 'SVGElement' cannot simultaneously extend types 'Element' and 'SVGElementInstance'.
  Named property 'nodeType' of types 'Element' and 'SVGElementInstance' are not identical.

12377 interface SVGElement extends Element, GlobalEventHandlers, DocumentAndElementEventHandlers, SVGElementInstance, HTMLOrSVGElement, ElementCSSInlineStyle {
                ~~~~~~~~~~
```

**Comment by joshoohaah** [comment]
I get the same error running locally..or using the azure pipeline yaml provided.   Is there a dependency on a prior node/typescript version?
![image](https://user-images.githubusercontent.com/8366405/73858262-b78d2500-47fd-11ea-9f4d-7f97130b43eb.png)

**Comment by joshoohaah** [comment]
![image](https://user-images.githubusercontent.com/8366405/73862366-181f6080-4804-11ea-8dd4-27fb35198ccf.png)

**Comment by joshoohaah** [comment]
it looks like its created by the TS extension referenced in `tsconfig.json`.
```
        "types": [
            "vss-web-extension-sdk"
        ]
```

issue where this is reported: https://github.com/microsoft/vss-web-extension-sdk/issues/112

**Comment by jessehouwing** [comment]
Fixed with: https://github.com/microsoft/AzureDevOps-WSJF-Extension/pull/24
