### ISSUE TITLE
Rounding WSJF value

### ISSUE THREAD

**Issue by mdmilroy** [microsoft/AzureDevOps-WSJF-Extension#18]
Could you add an option to round the value? Having 15+ decimal places clutters up the board tiles and looks clunky. Being able to implement a rounded output (say 2 decimals or select your own length) would be helpful.

**Comment by mhalkyer** [comment]
I would love this too! The current version displays too many decimals.
![wsjf_screenshot](https://user-images.githubusercontent.com/623531/75724993-8c3b1000-5cad-11ea-9634-3d821bc51255.PNG)

**Comment by EmilHovgaard** [comment]
I second this too....

**Comment by akirayukinns** [comment]
It is easy to add `Math.round()` into file https://github.com/microsoft/AzureDevOps-WSJF-Extension/blob/master/src/wsjf.tsx

**Comment by Alexander-Hjelm** [comment]
This feature is in the works :) Fixed by PR #33

**Comment by MOlausson** [comment]
Released in v.1.2.3.
