### ISSUE TITLE
How is this supposed to be compiled?

### ISSUE THREAD

**Issue by JamesDusenbery** [microsoft/AzureDevOps-WSJF-Extension#21]
Running into an issue where the solution compiles, but the JS for wsjfSettings is not found. There is no scripts/wsjfSettings JS fil in the solution. Is this generated by Gulp or something? Can more specific instructions be given on how to build this solution?

**Comment by akirayukinns** [comment]
You need build type script to javascript first.

**Comment by Alexander-Hjelm** [comment]
Assuming you already have Node v12.0.0+ installed:

```bash
npm install         # Install node dependencies
npm run build       # Compile the source code
npm run package     # Package the extension .vsix
```
