### ISSUE TITLE
WSJF calculation is not properly working

### ISSUE THREAD

**Issue by olenkasubota** [microsoft/AzureDevOps-WSJF-Extension#30]
The calculation is not properly working.
As you can see we created all the fields and properly mapped them to the extension. Can you please help resolve the issue?
Thanks in advance,
Olenka.

![image](https://user-images.githubusercontent.com/92101918/136396016-056189ec-8565-4f58-889d-c147056abd5f.png)

![image](https://user-images.githubusercontent.com/92101918/136395795-19192d36-a50b-44d8-963c-e0d07980f639.png)

![image](https://user-images.githubusercontent.com/92101918/136396338-86045fad-0831-4d38-9700-93fd2f1bb6ed.png)

**Comment by MOlausson** [comment]
@olenkasubota not yet but it's on the backlog so hope to have an update soon.

**Comment by olenkasubota** [comment]
@MOlausson, any updates on this?

**Comment by MOlausson** [comment]
@olenkasubota thanks for your patience. I've finally had time to repro this and found the issue. There's a logical error where the effort field configuration is overwritten when the RROE field is set. 

A work around is to

* first set all fields, 
* then change the effort field to some temporary field and save
* finally set the effort field again and save.

I'll work on getting a proper fix out asap but let me know if the work-around worked for you.

**Comment by olenkasubota** [comment]
Hi @MOlausson, looks like it's working now. Thanks for your help!
Will wait for the proper fix then :)

**Comment by MOlausson** [comment]
Fix has been released and reported working. Closing issue for now.

**Comment by cbadillava** [comment]
Hi, seems like this is not working again, do you have any report ? [WSJF calculation is not properly working](https://github.com/microsoft/AzureDevOps-WSJF-Extension/issues/30#top)
