### ISSUE TITLE
Extension of the WSJF calculation

### ISSUE THREAD

**Issue by staebchen0** [microsoft/AzureDevOps-WSJF-Extension#31]
Hi, is it possible to expand the WSJF calculation by two optional fields above and one optional field below?
```
a + b + c + d + e
-----------------------
f*g
```

**Comment by MOlausson** [comment]
@staebchen0 as you probably discovered already it's not. What would be the additional fields (dimensions) you have a need for?

**Comment by staebchen0** [comment]
In addition to the existing fields, I need 2 new fields (internal savings and external savings)

**Comment by AminTi** [comment]
I just tried to reproduce the issue and it works as expected,  if you  still facing the same issue let me know. We can schedule a Teams meeting.
