### ISSUE TITLE
Extension stopped working, unable to open settings page. 

### ISSUE THREAD

**Issue by Maxim-Krivobokov** [microsoft/AzureDevOps-WSJF-Extension#42]
Hello.
We are using this extension with TFS on prem. 2018

Last few days (after last update 17.06) unable to open WSJF settings page, with this message:
```
WSJF (Weighted Shortest Job First) by Microsoft DevLabs is taking longer than expected to load. Learn More about this extension, including available support options.
```
Also, all calculations no longer available.

Reinstallation did not help.

**Comment by LindaBoone42** [comment]
We are using the extension with Azure DevOps online and are experiencing the exact same issues since the update on 6/17

**Comment by LindaBoone42** [comment]
Any idea when this will be fixed?  This was a really useful addon but it hasn't worked since the update.

**Comment by kristow** [comment]
Any update on this, we are seeing the same issue with Azure DevOps Sever version 18.181.31626.1 (Azure DevOps Server 2020 Update 1.1)

**Comment by kl1mm** [comment]
I think it has something to do with the "New Boards Hubs". If I deactivate the feature in the "Preview features" the plugin works again.

**Comment by AminTi** [comment]
Thanks for reporting. it will be fixed in an upcoming release.
