### ISSUE TITLE
BUG - WSJF stopped working after the update 

### ISSUE THREAD

**Issue by LindaBoone42** [microsoft/AzureDevOps-WSJF-Extension#43]
Since the last update we have been unable to use this addon. It is no longer calculating and when you try to go to the settings screen it will not load.  We have let it sit for 10-15 minutes and still just shows:

![image](https://user-images.githubusercontent.com/73856365/178017631-2d739a5d-63c0-46e6-861d-a80d96c38351.png)

**Comment by AminTi** [comment]
Thanks for reporting. it will be fixed in an upcoming release.
