### ISSUE TITLE
Not able to open the Extension after install it

### ISSUE THREAD

**Issue by AsitJena** [microsoft/AzureDevOps-WSJF-Extension#44]
Hell Team,

We have installed the extension (AzureDevops-WSJF-Extension) on May 6, 2020 and configured the same... but latter on WSJF is not calculated the value as per the expectation, its coming with the value nothing. So we thought os something was missing on configuration, then we try to open the WSJF extension but we are not able to open the same. 

Could you please help us with this extension so that we can use this our projects, as WSJF already has been used by  many projects but from couples of days its not working. Please help with the same.

Note ; We have uninstalled this extension and installed it again but we are nit able to open this extension ( attached file).

![WSJF-Extension Loading Error](https://user-images.githubusercontent.com/42863668/178206953-28b02f21-9de9-4197-9769-a415b9b4520c.png)

**Comment by like-a-mike** [comment]
Hi Team,

same situation here, since the upgrade the extension is no longer working, please fix!

**Comment by AminTi** [comment]
Thanks for reporting. it will be fixed in an upcoming release.
