### ISSUE TITLE
WSJF only calculating on some work item types

### ISSUE THREAD

**Issue by JoshKiteAR** [microsoft/AzureDevOps-WSJF-Extension#46]
My client has two work item types in their Process (actually more): Feature and Discussion Item. Both are at the same Backlog level. Both have the exact same fields for Business Value, Time Criticality, RROE, Effort, and WSJF.

WSJF is being calculated for Features but not for Discussion Items. Is this user error or a bug?
Thanks

**Comment by MOlausson** [comment]
@JoshKiteAR I tried to repro this but for me it works. Are you using Azure DevOps service or server (on-prem)?

**Comment by JoshKiteAR** [comment]
This is the Azure DevOps service and **not** on-prem.
