### ISSUE TITLE
WSJF field not showing for all

### ISSUE THREAD

**Issue by jasontempleman-eaton** [microsoft/AzureDevOps-WSJF-Extension#50]
I am an ADO Org owner.  I've added this to a Feature work item, and I see the value fine.  A co-worker who is a contributor on the project that is using this does not see the value.  There was one time for a brief second as the feature was loaded it showed up but quickly disappeared.  If she changes the values, the new calculated value still does not show up.  Any thoughts on why I can see this and she cannot?

**Comment by AminTi** [comment]
Thanks for reporting, I will try to reproduce it and get back to you.

**Comment by AminTi** [comment]
Hi, if you still have the same problem let me know and we'll resolve it as soon as possible. Thank you for your support and understanding.

**Comment by jasontempleman-eaton** [comment]
I have not heard of any more issues so I think we are OK for now.  If this returns I'll reach out again.
Thanks
