### ISSUE TITLE
Allow for Team Project based configuration

### ISSUE THREAD

**Issue by damirvarga** [microsoft/AzureDevOps-WSJF-Extension#8]
Having the configuration on the Collection level is too generic. Please allow for the Team Project configuration, possibly with inheritance.

**Comment by deltics** [comment]
@ChristophLindemann it doesn't force consistency at all.  It simply forces all teams to use the same fields; nothing prevents teams from having different "scales" of values in those fields, thus subverting any attempt to treat WSJF as consistent across teams without making it apparent that they are.

If teams could use different fields in their WSJF calculation you could then make such variations apparent.

i.e. teams not using particular fields in their calculation would have no values in those fields, including in potentially different result fields.  Then you could ensure consistency by adopting policies that said "If you use WSJF approach X then you use fields ABC and D.  If you use approach Y then use fields HIJ and K."  Then at least you can reliably rank/compare all teams using different approaches.

Whether it is a good idea to have different teams using different WSJF calculations is a separate discussion.  But if they *are* then making this apparent is imho better than pretending that they aren't.
